test: Add a few trace tests
Signed-off-by: Diogo Behrens <db7@sdf.org>

diff --git a/scripts/dice b/scripts/dice
--- a/scripts/dice
+++ b/scripts/dice
@@ -1,6 +1,7 @@
 #!/bin/sh
 # Copyright (C) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 # SPDX-License-Identifier: 0BSD
+set -e
 
 if [ "$(uname)" = "Darwin" ]; then
     SO=dylib
@@ -9,21 +10,27 @@ else
 fi
 
 # find libdice
-PARDIR=$(readlink -f $(dirname "$0")/..)
-LIBDIR=$(readlink -f "$PARDIR")/lib
-
-if [ -f "$LIBDIR/libdice.$SO" ]; then
-    LIBDICE="$LIBDIR/libdice.$SO"
-    DICE_DIR="$LIBDIR/dice"
-    TSANO=$(which tsano)
-elif [ -f "$PARDIR/build/src/dice/libdice.$SO" ]; then
-    LIBDICE="$PARDIR/build/src/dice/libdice.$SO"
-    DICE_DIR="$PARDIR/build/src/mod"
-    TSANO="$PARDIR/deps/tsano/tsano"
-    TSANO_LIBDIR="$PARDIR/build/deps/tsano"
+if [ -z "$DICE_BUILD" ]; then
+	PARDIR=$(readlink -f $(dirname "$0")/..)
+	LIBDIR=$(readlink -f "$PARDIR")/lib
+	if [ -f "$LIBDIR/libdice.$SO" ]; then
+	    LIBDICE="$LIBDIR/libdice.$SO"
+	    DICE_DIR="$LIBDIR/dice"
+	    TSANO=$(which tsano)
+	elif [ -f "$PARDIR/build/src/dice/libdice.$SO" ]; then
+	    LIBDICE="$PARDIR/build/src/dice/libdice.$SO"
+	    DICE_DIR="$PARDIR/build/src/mod"
+	    TSANO="$PARDIR/deps/tsano/tsano"
+	    TSANO_LIBDIR="$PARDIR/build/deps/tsano"
+	else
+	    echo "could not find libdice.$SO"
+	    exit 1
+	fi
 else
-    echo "could not find libdice.$SO"
-    exit 1
+	LIBDICE="$DICE_BUILD/src/dice/libdice.$SO"
+	DICE_DIR="$DICE_BUILD/src/mod"
+	TSANO_LIBDIR="$DICE_BUILD/deps/tsano"
+	TSANO="$DICE_SOURCE/deps/tsano/tsano"
 fi
 
 if [ ! -f "$TSANO" ]; then
