Fix syntax error
Signed-off-by: Dmitry Ivanov <dmitry.ivanov1@huawei.com>

diff --git a/.github/workflows/dependants.yml b/.github/workflows/dependants.yml
--- a/.github/workflows/dependants.yml
+++ b/.github/workflows/dependants.yml
@@ -20,13 +20,16 @@ jobs:
     permissions:
       checks: write
     env:
-      COMMIT: ${{
-        github.event.pull_request.head.sha ||
-        github.event.push.head_commit.id ||
-        format('Event type is neither "push" nor "pull_request".')
-      }}
+      COMMIT: ${{ github.event.pull_request.head.sha || github.event.push.head_commit.id }}
       CHECK_NAME: ${{ matrix.dependant }}-${{ env.COMMIT }}-${{ github.run_attempt }}
     steps:
+      - name: Check if COMMIT is available
+        run: |
+          if [ -z "${{ env.COMMIT }}" ]; then
+            echo "Error: COMMIT not found. This workflow only supports push or pull_request events." >&2
+            exit 1
+          fi
+        shell: bash
       - name: Trigger ${{ matrix.dependant }} workflow
         uses: peter-evans/repository-dispatch@v3
         with:
@@ -36,7 +39,7 @@ jobs:
           client-payload: >
             {
               "sha": "${{ github.sha }}",
-              "commit": "${{ env.COMMIT }}"
+              "commit": "${{ env.COMMIT }}",
               "check_name": "${{ env.CHECK_NAME }}"
             }
       - name: Create empty check
